export const SAMPLE_TESTIMONIALS = [
  {
    id: 1,
    user_name: "Jessica K. – Saved 40%",
    rating: 5,
    comment: "Absolutely thrilled with the discounts on SavingHarbor. I found a 40% off coupon and got a great deal on something I was going to buy anyway!",
    avatar_url: "/images/avatars/user-1.webp",
    posted_at: "2025-08-10T12:00:00Z",
  },
  {
    id: 2,
    user_name: "Michael S. – Saved 35%",
    rating: 4,
    comment: "SavingHarbor consistently delivers. I’ve saved 35% on average in the last 3 months! It’s my go-to platform before I shop anywhere online.",
    avatar_url: "/images/avatars/user-2.webp",
    posted_at: "2025-07-01T09:30:00Z",
  },
  {
    id: 3,
    user_name: "Daniel P. – Saved 50%",
    rating: 5,
    comment: "Half off on my new gaming headset? YES. I’ve saved so much using SavingHarbor. Highly recommend it to anyone who loves saving smart.",
    avatar_url: "/images/avatars/user-3.webp",
    posted_at: "2025-06-20T15:45:00Z",
  },
{
    id: 4,
    user_name: "Adam R. – Saved 25%",
    rating: 4,
    comment: "SavingHarbor is amazing! I saved 25% on my last purchase thanks to their fantastic deals. It’s like finding digital treasure every time!",
    avatar_url: "/images/avatars/user-5.webp",
    posted_at: "2025-07-13T11:30:00Z",
  },
  {
    id: 5,
    user_name: "Emily M. – Saved 30%",
    rating: 5,
    comment: "I love the surprise savings! I never knew coupon hunting could be this fun. Just saved 30% on my tech gear thanks to SavingHarbor.",
    avatar_url: "/images/avatars/user-4.webp",
    posted_at: "2025-06-20T15:45:00Z",
  },
];
